### ISSUE TITLE
Cannot edit/move/delete blood machine room

### ISSUE THREAD

**Issue by UncagedFungus** [CorsixTH/CorsixTH#1524]
I wish to move the blood machine room.  When I use the 'Edit room/items' tool on this room the cursor turns to the 'zzz' as though waiting for something.  There was no doctor/patient in the room and noone queueing for the room.  
I would expect the normal cursor back after right-clicking the mouse but nothing happens.  I can open the saved games folder using Shift+L but cannot load one or do anything else.
Building a new blood machine room first doesn't work.
I have moved other rooms with no trouble.

I am using Windows 10.

Here's the save file from just before attempting relocation:
https://drive.google.com/open?id=1L6a0h4yCVuANks6KWE1ihrnHFNK_mrco

#### Gamelog.txt
Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Lua\humanoid_actions\meander.lua:68: bad argument #2 to 'findIdleTile' (number expected, got nil)
stack traceback:
        [C]: in method 'findIdleTile'
        Lua\humanoid_actions\meander.lua:68: in field '?'
        Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:607: in method 'queueAction'
        Lua\humanoid_actions\seek_room.lua:341: in field '?'
        Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:598: in method 'setNextAction'
        Lua\room.lua:97: in field 'callback'
        Lua\room.lua:906: in method 'deactivate'
        Lua\room.lua:915: in method 'tryToEdit'
        Lua\game_ui.lua:582: in function <Lua\game_ui.lua:555>
        (...tail calls...)
        Lua\app.lua:915: in function <Lua\app.lua:910>`
Warning: No event handler for buttonup

![image](https://user-images.githubusercontent.com/33372613/55968828-aa9eb400-5c74-11e9-9ce7-793d0b57faf2.png)

**Comment by TheCycoONE** [comment]
And which version of CorsixTH is this? 0.62 or the latest master, or something else?

**Comment by UncagedFungus** [comment]
I assume it's the latest. Checking the properties doesn't help.
![image](https://user-images.githubusercontent.com/33372613/55995094-83170e00-5cab-11e9-9b38-6c5802dd61b6.png)

**Comment by mugmuggy** [comment]
Same issue as #1183, the patient was seeking blood machine, the room didn't exist, patient was sent to research and callback wasn't removed. Room since built, but not sure why the build callback appears to be executing.

**Comment by UncagedFungus** [comment]
Have built second blood machine room.  No patients queueing for / on their way to first one.
Get something slightly different:

Lua\world.lua:1548: bad argument #2 to 'findDistance' (number expected, got nil)
stack traceback:
        [C]: in method 'findDistance'
        Lua\world.lua:1548: in method 'getPathDistance'
        Lua\world.lua:1779: in function <Lua\world.lua:1765>
        (...tail calls...)
        Lua\humanoid_actions\seek_room.lua:249: in field '?'
        Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:598: in method 'setNextAction'
        Lua\room.lua:97: in field 'callback'
        Lua\room.lua:906: in method 'deactivate'
        Lua\room.lua:915: in method 'tryToEdit'
        Lua\game_ui.lua:582: in function <Lua\game_ui.lua:555>
        (...tail calls...)
        Lua\app.lua:915: in function <Lua\app.lua:910>

**Comment by TheCycoONE** [comment]
If you play in window mode it shows the version in the title bar. It is also near the top of the gamelog.

**Comment by mugmuggy** [comment]
#1484 should fix this scenario from occuring as it removes the callbacks for the build room when sent to research. I'll need to finish cleaning that up.

**Comment by UncagedFungus** [comment]
That's not clear enough for me.  What exactly do I need to do?

**Comment by TheCycoONE** [comment]
@UncagedFungus he was pointing out a patch in progress not a workaround. A workaround would probably be never send a patient to research?

**Comment by UncagedFungus** [comment]
Still doesn't make sense to me.  Please tell me what I need to do, step by step.  I'm autistic, not stupid.

**Comment by wolfy1339** [comment]
Nobody is calling anyone stupid.

There's nothing for you to do right now, they're just pointing out that there's a code patch that will be included in the next update.

Please just sit back and wait patiently

**Comment by UncagedFungus** [comment]
Thanks @wolfy1339 for translating.

**Comment by mugmuggy** [comment]
Merged
