### ISSUE TITLE
Endcondition check seems incorrectly implemented

### ISSUE THREAD

**Issue by kl-mel** [CorsixTH/CorsixTH#2432]
### Describe the issue

Hello, I don't know if this is a bug with the game but I'm one of the custom corsixth levels "Dethsdaw".

I have met all the requirements (above 900 reputation, 90% cured, hospital value, bank balance which is a target of 450,000 and I'm now at over 3 million haha) but the level never ends.

I am aware of the fact that if you hold down z to fast forward it won't register a game win, but that isn't the problem here.

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. wait until the first of the month, where usually the level would end

3.

### Expected Behaviour

I expected the level to end as I have matched all the requirements.

### Save Game

Save game attached to report: yes
[dethsdaw2.sav.zip](https://github.com/CorsixTH/CorsixTH/files/12790900/dethsdaw2.sav.zip)

### CorsixTH Version

0.66

### Operating System

macOS monterey

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x86_64, audio: true, os: macos
SDL renderer: metal
Lua 5.4 run with api version: 2682, game version: v0.66, savegame version: 170
Created game with savegame version 170.
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to remove nonexistent room build callback (function: 0x60000344a5e0) from humanoid (table: 0x600008855d80).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001defb10) from humanoid (table: 0x600008855d80).
Warning: Trying to remove nonexistent staff callback (function: 0x6000034481e0) from humanoid (table: 0x600008855d80).
Warning: Trying to resolve door deadlock at (39, 75)
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to remove nonexistent room build callback (function: 0x6000035dd500) from humanoid (table: 0x60000445cc80).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001c666d0) from humanoid (table: 0x60000445cc80).
Warning: Trying to remove nonexistent staff callback (function: 0x6000035dcf00) from humanoid (table: 0x60000445cc80).
Warning: Trying to remove nonexistent room build callback (function: 0x6000034721c0) from humanoid (table: 0x600008b663c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001cce580) from humanoid (table: 0x600008b663c0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003472160) from humanoid (table: 0x600008b663c0).
Warning: Trying to remove nonexistent room build callback (function: 0x600003479da0) from humanoid (table: 0x600008a69ec0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001c0b120) from humanoid (table: 0x600008a69ec0).
Warning: Trying to remove nonexistent staff callback (function: 0x60000347a4c0) from humanoid (table: 0x600008a69ec0).
Warning: Trying to remove nonexistent room build callback (function: 0x60000344b1e0) from humanoid (table: 0x600008b44ec0).
Warning: Trying to remove nonexistent room remove callback (function: 0x6000002ba190) from humanoid (table: 0x600008b44ec0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003449200) from humanoid (table: 0x600008b44ec0).
Warning: Trying to remove nonexistent room build callback (function: 0x6000035450e0) from humanoid (table: 0x600008ff8100).
Warning: Trying to remove nonexistent room remove callback (function: 0x6000002f9500) from humanoid (table: 0x600008ff8100).
Warning: Trying to remove nonexistent staff callback (function: 0x600003547c00) from humanoid (table: 0x600008ff8100).
Warning: Trying to remove nonexistent room build callback (function: 0x600003456760) from humanoid (table: 0x600008f94a40).
Warning: Trying to remove nonexistent room remove callback (function: 0x6000003d7240) from humanoid (table: 0x600008f94a40).
Warning: Trying to remove nonexistent staff callback (function: 0x600003456700) from humanoid (table: 0x600008f94a40).
Warning: Trying to remove nonexistent room build callback (function: 0x6000035254a0) from humanoid (table: 0x600004c883c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600000203f30) from humanoid (table: 0x600004c883c0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003524600) from humanoid (table: 0x600004c883c0).
Warning: Trying to remove nonexistent room build callback (function: 0x600003466760) from humanoid (table: 0x600008ad8e40).
Warning: Trying to remove nonexistent room remove callback (function: 0x600000109cb0) from humanoid (table: 0x600008ad8e40).
Warning: Trying to remove nonexistent staff callback (function: 0x600003466700) from humanoid (table: 0x600008ad8e40).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to remove nonexistent room build callback (function: 0x600003444c60) from humanoid (table: 0x600008d794c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x60000019a730) from humanoid (table: 0x600008d794c0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003444c00) from humanoid (table: 0x600008d794c0).
Warning: Trying to resolve door deadlock at (67, 49)
Warning: Trying to remove nonexistent room build callback (function: 0x6000035260a0) from humanoid (table: 0x600008d63e40).
Warning: Trying to remove nonexistent room remove callback (function: 0x6000003c7cf0) from humanoid (table: 0x600008d63e40).
Warning: Trying to remove nonexistent staff callback (function: 0x600003527a20) from humanoid (table: 0x600008d63e40).
Warning: Trying to remove nonexistent room build callback (function: 0x60000342b840) from humanoid (table: 0x600008d7b6c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001c79050) from humanoid (table: 0x600008d7b6c0).
Warning: Trying to remove nonexistent staff callback (function: 0x60000342ac40) from humanoid (table: 0x600008d7b6c0).
Warning: Trying to remove nonexistent room build callback (function: 0x600003461fe0) from humanoid (table: 0x600000989b80).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001d19fe0) from humanoid (table: 0x600000989b80).
Warning: Trying to remove nonexistent staff callback (function: 0x600003461f20) from humanoid (table: 0x600000989b80).
Warning: Trying to remove nonexistent room build callback (function: 0x6000034c2520) from humanoid (table: 0x600000e59180).
Warning: Trying to remove nonexistent room remove callback (function: 0x600000315e30) from humanoid (table: 0x600000e59180).
Warning: Trying to remove nonexistent staff callback (function: 0x6000034c24c0) from humanoid (table: 0x600000e59180).
Warning: Trying to remove nonexistent room build callback (function: 0x600003594d20) from humanoid (table: 0x600000c47400).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001ee0cf0) from humanoid (table: 0x600000c47400).
Warning: Trying to remove nonexistent staff callback (function: 0x600003595aa0) from humanoid (table: 0x600000c47400).
Warning: Trying to remove nonexistent room build callback (function: 0x6000034451a0) from humanoid (table: 0x600000ed68c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x6000002bc8a0) from humanoid (table: 0x600000ed68c0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003445140) from humanoid (table: 0x600000ed68c0).
Warning: Trying to resolve door deadlock at (59, 60)
Warning: Trying to remove nonexistent room build callback (function: 0x60000340e0a0) from humanoid (table: 0x600000afd2c0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600000153c30) from humanoid (table: 0x600000afd2c0).
Warning: Trying to remove nonexistent staff callback (function: 0x60000340f540) from humanoid (table: 0x600000afd2c0).
Warning: Trying to resolve door deadlock at (59, 53)
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to resolve door deadlock at (73, 58)
Warning: Trying to remove nonexistent room build callback (function: 0x600003bc0660) from humanoid (table: 0x600008b4fec0).
Warning: Trying to remove nonexistent room remove callback (function: 0x600000374d80) from humanoid (table: 0x600008b4fec0).
Warning: Trying to remove nonexistent staff callback (function: 0x600003bc0540) from humanoid (table: 0x600008b4fec0).
Warning: Trying to remove nonexistent room build callback (function: 0x60000341dbc0) from humanoid (table: 0x6000009b9640).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001e27090) from humanoid (table: 0x6000009b9640).
Warning: Trying to remove nonexistent staff callback (function: 0x60000341db60) from humanoid (table: 0x6000009b9640).
Warning: Trying to resolve door deadlock at (59, 60)
Warning: Trying to remove nonexistent room build callback (function: 0x60000353c660) from humanoid (table: 0x600008de7280).
Warning: Trying to remove nonexistent room remove callback (function: 0x600001d69560) from humanoid (table: 0x600008de7280).
Warning: Trying to remove nonexistent staff callback (function: 0x60000353cc60) from humanoid (table: 0x600008de7280).
Warning: Trying to resolve door deadlock at (82, 72)
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to resolve door deadlock at (59, 60)
Warning: Trying to resolve door deadlock at (67, 53)
Warning: Trying to resolve door deadlock at (59, 48)
Warning: Trying to resolve door deadlock at (67, 49)
Warning: Trying to resolve door deadlock at (59, 60)
Warning: Trying to resolve door deadlock at (59, 60)
Warning: Trying to resolve door deadlock at (77, 29)
Warning: Trying to resolve door deadlock at (72, 63)
Warning: Trying to resolve door deadlock at (68, 43)
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Warning: Trying to resolve door deadlock at (68, 43)
Warning: Trying to resolve door deadlock at (67, 49)
Warning: Trying to resolve door deadlock at (81, 79)
Warning: Trying to resolve door deadlock at (68, 43)
Warning: Trying to resolve door deadlock at (59, 56)
Savegame version is 170 (v0.66), originally it was 170 (v0.66).

Empty action queue!
Last action: seek_toilets
stack traceback:
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:630: in method '_handleEmptyActionQueue'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:469: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...MacOS/../Resources/Lua/humanoid_actions/seek_toilets.lua:37: in field '?'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:476: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...ntents/MacOS/../Resources/Lua/humanoid_actions/queue.lua:350: in local 'on_interrupt'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:484: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...s/MacOS/../Resources/Lua/humanoid_actions/use_object.lua:360: in local 'timer_function'
	.../CorsixTH.app/Contents/MacOS/../Resources/Lua/entity.lua:216: in method 'tick'
	...s/CorsixTH.app/Contents/MacOS/../Resources/Lua/world.lua:1085: in method 'onTick'
	...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1130: in function <...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1127>
	(...tail calls...)
	...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1030: in function <...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1025>
Error in timer handler: 
...orsixTH.app/Contents/MacOS/../Resources/Lua/graphics.lua:337: bad argument #1 to 'sizeOf' (string expected, got table)
stack traceback:
	[C]: in method 'sizeOf'
	...orsixTH.app/Contents/MacOS/../Resources/Lua/graphics.lua:337: in method 'sizeOf'
	...ntents/MacOS/../Resources/Lua/dialogs/confirm_dialog.lua:60: in local 'constructor'
	...s/CorsixTH.app/Contents/MacOS/../Resources/Lua/class.lua:74: in global 'UIConfirmDialog'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:632: in method '_handleEmptyActionQueue'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:469: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...MacOS/../Resources/Lua/humanoid_actions/seek_toilets.lua:37: in field '?'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:476: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...ntents/MacOS/../Resources/Lua/humanoid_actions/queue.lua:350: in local 'on_interrupt'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:484: in method 'startAction'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:577: in method 'finishAction'
	...s/MacOS/../Resources/Lua/humanoid_actions/use_object.lua:360: in local 'timer_function'
	.../CorsixTH.app/Contents/MacOS/../Resources/Lua/entity.lua:216: in method 'tick'
	...s/CorsixTH.app/Contents/MacOS/../Resources/Lua/world.lua:1085: in method 'onTick'
	...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1130: in function <...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1127>
	(...tail calls...)
	...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1030: in function <...ons/CorsixTH.app/Contents/MacOS/../Resources/Lua/app.lua:1025>
```

**Comment by lewri** [comment]
I think this is a  bug fixed in 0.67, failed action queue. Have you tried loading an autosave from before the humanoid toilet crash in 0.67?

**Comment by kl-mel** [comment]
[dethsdaw2 2.sav.zip](https://github.com/CorsixTH/CorsixTH/files/12800609/dethsdaw2.2.sav.zip)

Sorry, this should be the correct save file. It looks like all my autosaves are unfortunately from after this save file.

Have now downloaded 0.67 but still doesn't seem to be letting me finish the level. Ah well, thank you for your suggestions! If you happen to know the progression of levels I might just select the next one manually! (Assuming that's possible)

**Comment by tobylane** [comment]
You've cured 90% of your patients, but you need to be over this to beat the goal. I think this is our error.

**Comment by kl-mel** [comment]
Good spot, thank you! I'll persevere.

**Comment by Alberth289346** [comment]
Has the error been solved?

**Comment by Alberth289346** [comment]
Changed the title to "Endcondition check seems incorrectly implemented"

**Comment by kl-mel** [comment]
> Has the error been solved?

The level did end as expected once I hit 91% cured so your title change is correct.

**Comment by Alberth289346** [comment]
I don't know what the requirement was, did it ask for "90% cured" or "more than 90% cured" ?

**Comment by lewri** [comment]
We're using `>` and `<` rather than `<=` and `>=` for win/lose conditions. Our level config files currently aren't geared to support those inequalities (than could be). But it'd be easier just to decide if to use `< >` or `<= >=`

https://github.com/CorsixTH/CorsixTH/blob/0202eb30d973b79a321a7d3c5eebe12eff2afc30/CorsixTH/Lua/world.lua#L1433-L1485

**Comment by kl-mel** [comment]
> I don't know what the requirement was, did it ask for "90% cured" or "more than 90% cured" ?

"You need to have treated 90% of the visitors to your hospital"

**Comment by Alberth289346** [comment]
``` lua
hospital.lua
1867:  self.percentage_cured = math.round(cured)
```
Cured percentage is rounded, so `90.2%`  is rounded down and does not count with a comparison that excludes equality. On the other hand, `90.51%` is rounded up to `91%` already and thus claiming `91%` too early.

**Comment by lewri** [comment]
I think you don't need to fix both issues for this case (as the chance of landing on exactly x% is probably extremely rare). It would be enough to store percentage_cured as the raw value; then round it at the time it needs to be rounded (e.g. in progress report I'm assuming).
Truly, you would want both, but just making that change in hospital for as the initial fix will be good enough until we decide to expand (if we do) the inequalities support.

**Comment by tobylane** [comment]
Hospital value may be a better example of one part of the issue, as it can be exactly matched. Here's a sav that only meets the requirement for winning, including the held radiator, [Wintest.sav.zip.](https://github.com/CorsixTH/CorsixTH/files/12837960/Wintest.sav.zip) If the comparison here is just a < then equalling the goal counts as a win. https://github.com/CorsixTH/CorsixTH/blob/0202eb30d973b79a321a7d3c5eebe12eff2afc30/CorsixTH/Lua/world.lua#L1473

**Comment by lewri** [comment]
> Hospital value may be a better example of one part of the issue, as it can be exactly matched. Here's a sav that only meets the requirement for winning, including the held radiator, [Wintest.sav.zip.](https://github.com/CorsixTH/CorsixTH/files/12837960/Wintest.sav.zip) If the comparison here is just a < then equalling the goal counts as a win.
> 
> https://github.com/CorsixTH/CorsixTH/blob/0202eb30d973b79a321a7d3c5eebe12eff2afc30/CorsixTH/Lua/world.lua#L1473

I think it's down to the wording of the goal condition. If its a `meet/at least x` then it should respect being spot on the value. If it's `exceed/below` then it needs to not be at the threshold. I'm not sure if you're addressing this in #2484 at all?

**Comment by tobylane** [comment]
Yes. The same sort of check is used, but with the starting position of not win or lose. So meeting the goal does mean win or lose.

**Comment by tobylane** [comment]
No, scratch that, it isn't dealt with correctly. Thanks for noticing that.
