### ISSUE TITLE
[Bug] Paging Handyman to repair machine does not visibly mark it for repair

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2949]
### Describe the issue

When the player calls a handyman to fix a machine (by clicking the Page Handyman button in the machine's popup window), the machine is not being visibly marked for repair. The animated Machine Due For Repair icon does not appear above the machine, and the machine's name is not surrounded by brackets in the popup. There is nothing to indicate that the machine is currently in the repair queue, even after a Handyman starts making his way towards the room to fix it.

<img width="1442" height="932" alt="Image" src="https://github.com/user-attachments/assets/964682de-b8bf-4419-be50-42b6fe19af4e" />

### Steps to Reproduce

1. Click on any machine to open the machine's popup window
2. Click the Page Handyman button

### Expected Behaviour

In Theme Hospital, when the user clicks the Page Handyman button for a machine:

1. The Machine Due For Repair icon appears above the machine (an animated gear that repeatedly splits into halves and separates)
2. The machine's name becomes surrounded by brackets in the popup window.

<img src="https://github.com/user-attachments/assets/6f7c074f-2ddd-40eb-85be-23045871db51" />

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68.0, 0.69.0

### Operating System

Windows 10

### Theme Hospital Version

CD

### Gamelog.txt

```yaml

```

**Comment by ARGAMX** [comment]
Also my report to this discrepancy too:

I discovered discrepancy with that gear icon between TH and CTH.

In TH this icons means that YOU added this machine in list for repair.
In CTH this icons means that some handyman assigned to fix that machine. (but if we take into account the **MandrakeHorse** screenshot, where Handyman going to fix machine, this statement is also not true)

So in TH you always immediately see that gear icon on press  "Call Handyman for repair" button. You don't even need to have any hired Handyman. And this gear can appear only after you pressed button. If any Handyman goes to fix machine by himself without button, you won’t see this icon.

In CTH you will never see that gear icon if you don't hired any Handyman. Even if you press the "Call Handyman for repair" button 100 times. Also, due to the possible busy schedule of the Handyman, this icon may appear with a delay only after some Handyman will take on this task. If any Handyman goes to fix machine by himself without button, you will see that icon regardless on the fact that you didn't press the button.

So this icon in CTH doesn't mean the same thing as it did in the original TH.
And besides, there's no real consistent feedback on pressing "Call Handyman for repair" button in CTH.

In CTH you can poke button senselessly and not understand why is nothing happening, expecting the same behavior as in the original TH.

The save where behavior can be detected:

[gear_on_repair_not_show_imidietly.sav.zip](https://github.com/user-attachments/files/21502802/gear_on_repair_not_show_imidietly.sav.zip)

**Comment by MandrakeHorse** [comment]
Once we've fixed the bug that prevents the gear icon from ever appearing, we can discuss whether we should copy Theme Hospital's behaviour as a separate issue. (Our philosophy is that we should follow Theme Hospital's behaviour unless there's a good reason to do it differently, I personally prefer marking the machine as "Waiting in the repair queue" for immediate feedback. One option could be to create a new icon for "Next in line for repair", similar to how epidemic patients can be marked as "Next in line for vaccination".)

**Comment by ARGAMX** [comment]
Also can be reproduced in this save.
v0.69.0

[repair_gear_does_not_appear.sav.zip](https://github.com/user-attachments/files/21666796/repair_gear_does_not_appear.sav.zip)

<img width="569" height="372" alt="Image" src="https://github.com/user-attachments/assets/161daeb8-5c53-4d3b-a2fc-71e56c2f60ea" />

1. Load savegame.
2. Dismiss the handyman in the upper left corner of the screen. He only one who serving this part of hospital.
3. Press the gear button on the Slack Tongue Slicer and the Fracture Fixer.
4. Observe that the gear icon will never appear.

If you retry experiment without handyman dismiss, then the gear icon will appear only above one of the machine.

**Comment by ShiroAka** [comment]
Here is the culprit, I think

<img width="413" height="328" alt="Image" src="https://github.com/user-attachments/assets/eb1d9787-484e-4720-8209-d65c35ee180c" />

**Comment by ARGAMX** [comment]
I am experiencing this bug again. 
3006 not resolved it completely.

Load save and go through all machines and press gear button. 
You will see gear only above Cardio. 

Save game require save game version not below than 240.
[0.70.240.repair.the_gear_is_not_displayed.sav.zip](https://github.com/user-attachments/files/25388429/0.70.240.repair.the_gear_is_not_displayed.sav.zip)

<img width="437" height="312" alt="Image" src="https://github.com/user-attachments/assets/74eb50d0-cefc-45f7-b78f-988eee9bf25a" />

**Comment by Alberth289346** [comment]
Yesterday, I checked all machines of level 4 of the game for having staff position markers for handyman repairs. I found that you cannot get a handyman to repair a machine before it is used. It doesn't give a warning or message for it or so, the gears are just not shown (and the handyman never arrives to repair it).

I didn't test the blood machine (it's apparently not in level 4), although I don't expect it to be have very different from other machines.

**Comment by ARGAMX** [comment]
> Yesterday, I checked all machines of level 4 of the game for having staff position markers for handyman repairs. I found that you cannot get a handyman to repair a machine before it is used. It doesn't give a warning or message for it or so, the gears are just not shown (and the handyman never arrives to repair it).
> 
> I didn't test the blood machine (it's apparently not in level 4), although I don't expect it to be have very different from other machines.

If a machine `Times Used` = 0, that's perfectly normal and the button really doesn't do anything.

But in my save, the machines are bit worn out and require repair but the the icon still doesn't appear.

**Comment by ARGAMX** [comment]
Fixed this in #3255
Also did some refactoring to make it harder to break it again.
