### ISSUE TITLE
render_attach_position does not work with use_animate_from_use_position

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#448]
_From [edvin.li...@gmail.com](https://code.google.com/u/103389254238552841029/) on June 14, 2010 15:47:39_

What steps will reproduce the problem? 1. Try to for example make the lecture chair be correctly rendered against a wall when in use by defining render_attach_position as a table. What is the expected output? What do you see instead? A double render is made, most likely because this object uses the use_animate_from_use_position variable.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=310_

**Comment by lewri** [comment]
@TheCycoONE I think you made changes to rendering since 2013. Is this still relevant/would it fix any current glitches still?

**Comment by TheCycoONE** [comment]
Still bugged.

**Comment by ARGAMX** [comment]
1. What are the consequences of this problem?
2. Is there any videos or pictures illustrating this problem?
3. Are there more detailed steps to reproduce this problem? I don't understand how to reproduce this according to the description given.

**Comment by Alberth289346** [comment]
Rendering the graphics is done in a diagonal order of tiles (horizontal lines of tiles at the screen). To get a correct result, all background must have been drawn earlier. That isn't always the case with multi-tile animations, depending on what objects are near each other, and depending on their orientation.

One attempt to fix things is by re-rendering a previous tile in some cases. This caused other glitches (the nurse walking in front of the bed at least).

The *single* (I think) render attach point is a different attempt. It 'moves' the animation to a different tile by changing the rendering offset relative to the new tile. Since the order of rendering tiles is fixed, a change of tile means that the animation is drawn at a different point in time.
Doing that correctly means that the background is drawn earlier, and it eliminates a glitch.

Render attach points usually work relative to tile (0, 0). An animate-from-use position uses the tile of the humanoid as animation tile. That may not be tile (0, 0).  

I am not sure why the "animate from use" thing exists. It makes sense for walking I guess, but I don't see much other use.

For all objects you know where the object is, and to me it makes more sense to derive humanoid position and animation position from the object position instead of saying "let's paint the object from the tile of the humanoid". But I am possibly very wrong here. I haven't looked in detail to positions of tiles for animations.

**Comment by ARGAMX** [comment]
Ok, so based on the description kindly provided by Albert, this issue looks like a problem from the `[META] Graphical Glitches in game` group, most of which are dedicated to objects graphically overlapping each other where they shouldn't.

But for some reason this issue not linked to META. Why?
Is this is some special unique problem here?
Or is this one of those problems that can be solved if we implement a more advanced rendering method that takes into account the nuances described by Albret?

And also, as I understand it, this is not a Lua-level task, but a C++-level one? Correct?

**Comment by Alberth289346** [comment]
> But for some reason this issue not linked to META. Why?

Likely, the meta issue focuses on actual graphic glitch issues. I wasn't aware of this issue as well, mostly because you first need a working algorithm before you can decide what to do with code around it.

> Is this is some special unique problem here?

It's probably unique, as in, we don't have other issues about it. Not sure that counts as special. My first guess is 'no'.

> Or is this one of those problems that can be solved if we implement a more advanced rendering method ...

No idea. Object definitions like in the `objects` directory are needed to some extent since you need to know some stuff in order to use it in the game. Whether everything there is really necessary, I have no idea. There are no good descriptions (the wiki has some), and no explanations why they are there.
The wiki is also not complete.

At the same time, I know things are missing there too. The handyman animations and positions have been hacked in the `use_object` action rather than being defined in in the object definitions. I also know we're nowhere for accepting a free set of animations there. (Imagine a second set of animations, with different animation numbers and rendering offsets. We have no spot for that.)

> And also, as I understand it, this is not a Lua-level task, but a C++-level one? Correct?

Not correct. object definitions don't exist at all in C++, they are strictly Lua. The `humanoid_actions/use_object.lua` file handles it.

**Comment by ARGAMX** [comment]
> 3. Are there more detailed steps to reproduce this problem? I don't understand how to reproduce this according to the description given.

Can someone explain how to reproduce this and how to understand during the reproduction process that the result is somehow not what it should be?
It seems there’s still not enough context regarding the task.
I think the task name is bad.
Since the last discussion, issue hasn’t moved at all?
The issue is already 16 years old. 🎂
It seems the issue is more dead than alive.
